- name: get OS release
  raw: lsb_release -c 
  register: lsb_release

- name: set os release variable
  set_fact:
    os_release: "{{ lsb_release.stdout.split(':')[1] | trim }}"

- name: Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
  raw: systemctl disable --now {{item}}
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.timer'
  when: os_release == 'bionic'

- name: Reload systemctl daemon to apply the new changes
  raw: systemctl daemon-reload
  when: os_release == 'bionic'

- name: Wait for unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true
  when: os_release == 'bionic'

- name: Purge unattended upgrades
  raw: apt-get -y purge unattended-upgrades   
  when: os_release == 'bionic'

- name: Update apt cache
  raw: apt-get -y update

- name: If needed, install Python
  raw: apt-get -y install python python-pip

- name: set hostname
  hostname:
    name: "{{hostname}}"

- name: gather facts
  setup: 

- name: Add hostname to hosts file
  lineinfile: 
    dest: /etc/hosts 
    line: "{{ location_ip if location_ip is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{hostname}}" 
    state: present
